### ISSUE TITLE
Selecting RoI

### ISSUE THREAD

**Issue by abylikhsanov** [carlosmccosta/dynamic_robot_localization#23]
Hi,

If I have predefined static objects in specific locations of occupancy map, is it possible to select a region of interest for the ICP? So instead of trying to match the whole visible map, it will only try to match the selected RoI of the map

**Comment by carlosmccosta** [comment]
Good morning,

You can select regions of interest using the [crop_box filter](https://github.com/carlosmccosta/dynamic_robot_localization/blob/noetic-devel/yaml/schema/drl_configs.yaml#L273).

The RoIs can be configured to include points inside or outside the crop_box (configured with the `invert_selection` parameter).

You can have several crop_box filters for refining the regions that you want to include / exclude points.

But keep in mind that the logical operation is AND, not OR.

Each crop_box filter will select points inside / outside.

As such, removing points from several RoIs is possible, but selecting points that are inside several non overlapping crop_boxes is currently not supported (it will result in an empty point cloud).

This filter can be applied in different coordinate systems depending on the parent namespace:
- `ambient_pointcloud` and `ambient_pointcloud_feature_registration` -> original sensor frame
- `ambient_pointcloud_map_frame` and `ambient_pointcloud_map_frame_feature_registration` -> map frame
- `ambient_pointcloud_custom_frame` -> other custom TF frame specified in the `custom_frame_id` parameter

You can also crop the occupancy map with crop_box, by placing the filter inside `reference_pointcloud`.

More info in the filters section in [drl_configs.yaml](https://github.com/carlosmccosta/dynamic_robot_localization/blob/noetic-devel/yaml/schema/drl_configs.yaml#L222).

Example for applying a single RoI in the map frame:
```
filters:
    ambient_pointcloud_map_frame:
        crop_box:                             # Allows prefix and postfix of letters / numbers to ensure processing order
            box_min_x: -10.0
            box_min_y: -10.0
            box_min_z: -10.0
            box_max_x: 10.0
            box_max_y: 10.0
            box_max_z: 10.0
            box_translation_x: 0.0
            box_translation_y: 0.0
            box_translation_z: 0.0
            box_rotation_roll: 0.0
            box_rotation_pitch: 0.0
            box_rotation_yaw: 0.0
            invert_selection: false           # If false -> selects points outside the box
            filtered_cloud_publish_topic: ''
```

Have a nice day :)
